### PR TITLE
Add coment - implemented

### PR DESCRIPTION
**Pull request by Szpytma**

### CODE REVIEW

**Review by roisinoreilly — CHANGES_REQUESTED** [review]
great start Pawel! I have a few thing I'd like you to look at and make changes from a user experience perspective:

- if you try throttling the network to offline when you post a comment, the comment is still optimistically rendered, if the user navigated away from the page after losing connection they would assume their comment has been posted successfully, an error handler would be good here
- it would be nice if there was a message to alert the user that their comment has been posted successfully
- (this is relating to a previous ticket) you can only vote once on a review either up or down, what if the user changed their mind?
- if the network is slow 3G the user is prevented from submitting the same comment twice only by the fact they have to select a user again from the dropdown, if you made it so that the user was already logged in the comment would be posted twice to the database. It would be a better user experience to have the comment buttom/form disabled while it is being posted or a loading message
- should the number of comments be displaying on your review card? Each one says 0

After you've had a look at these things send us another PR :)

**Comment by Szpytma** [comment]
@roisinoreilly all things are updated now. 

Apart from the last comment - it is cased to ticket 15. which is editing get/reviews to contain comment_count

**Comment by Szpytma** [comment]
FYI - I am restoring the table to the original data set from time to time.

**Review by alexdevdavis — APPROVED** [review]
Happy to approve comments form. Nice one 👍 
FYI, the like / dislike thing ... we have 3 options: to like, dislike or do nothing (neutral). But once we've clicked one button, the other can only be used to get back to neutral, rather than allowing us access to the full range of 3 options. Consider fixing this.

**Pull request merged**
